version: 2
workflows:
  version: 2
  build:
    jobs:
      - build-znc1.6
      - build-znc1.7

jobs:
  build: &build
    docker:
      - image: znc

    steps:
      - checkout
      - run:
          /opt/znc/bin/znc-buildmod palaver.cpp

  build-znc1.6:
    <<: *build
    docker:
      - image: znc:1.6

  build-znc1.7:
    <<: *build
    docker:
      - image: znc:1.7
